- name: Install Redis component
  hosts: redis
  become: yes
  tasks:
    - name: Install Redis repo
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.9.rpm
        state: present
        disable_gpg_check: true

    - name: Enable Redis 6.2 module
      ansible.builtin.command:
        cmd: yum module enable redis:remi-6.2 -y

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Remove any broken bind lines
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind0.0.0.0 -::1'
        state: absent

    - name: Ensure correct bind line
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: 'bind 0.0.0.0 ::1'
        state: present

    - name: Disable protected-mode for remote access
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode'
        line: 'protected-mode no'
        state: present

    - name: Start and enable Redis service
      ansible.builtin.service:
        name: redis
        state: restarted
        enabled: yes
